# Generated by Django 6.0 on 2025-12-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_alter_course_id_alter_student_id_alter_trainer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
